### ISSUE TITLE
Range and Resolution

### ISSUE THREAD

**Issue by matgrioni** [davidson16807/fast-multipole-method#2]
I am having issues using the library and it is dependent on the values used for range and resolution. According to documentation range is the "maximum distance considered by the model. It is the distance at which two particles can no longer interact with one another."

My code is below in coffeescript. For large range values this code works, but for smaller range values `field.value(entity)` returns undefined. I feel like range is actually affecting how the grids are created, and not just a way of calculating the force field for far away objects.

```
repulse: ->

        resolution = 10
        range = 2 * @size

        repulsion = @repulsion
        field = FMM.VectorField2 resolution, range, (offset, particle) ->
            distance = Math.sqrt(offset.x * offset.x + offset.y * offset.y)
            acceleration = (repulsion * particle.m) / (10 + distance * distance)

            normalized = {
                x: offset.x / distance,
                y: offset.y / distance
            }

            return {
                x: acceleration * normalized.x,
                y: acceleration * normalized.y
            }

        for entity in @entities.items
            field.add_particle(entity, { m: entity.m })

        for entity in @entities.items
            value = field.value(entity)
            entity.fx -= entity.m * value.x
            entity.fy -= entity.m * value.y
```

**Comment by davidson16807** [comment]
You're correct, `range` and `resolution` determine the number of nested grids that are created. That's why they're passed to the constructor and not the `value()` function.

The reason `field.value(entity)` returns `undefined` and not `{x:0,y:0}` is because it doesn't know that `{x:0,y:0}` is the default value for the field. It could be a scalar, or a 3d vector, or something more complex. It relies on grid contents to determine value type, but if `range` is small enough, then it will never try to read from the grid, so it returns undefined. 

The issue can be resolved by creating another attribute in Field2 and Field3 that represents the "default" or "background" value of the field. The background value gets added onto anything else,  so if `{x:1,y:1}` is the background to a force field, then there's a background force that pulls everything evenly to one corner of the field. This would increase functionality and simplify some code under the hood.

**Comment by davidson16807** [comment]
I've added this background value to the `background-value` branch. Check it out.

**Comment by matgrioni** [comment]
Thanks for the update. The explanation cleared up why the grid was not initialized to some default value.
